[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
physics_engine_bevy = {path = "../../crates/physics_engine_bevy"}
bevy = { version = "0.14.0", features = ["bevy_dev_tools"] }
bevy_prototype_lyon = "0.12.0"
bevy_mod_picking = "0.20.1"
bevy_egui = "0.28.0"

