name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: rust-toolchain

      - name: Run Cargo fmt
        run: |
          for dir in $(find crates examples -name "Cargo.toml" -exec dirname {} \;); do
            echo "Checking formatting in $dir"
            (cd "$dir" && cargo fmt -- --check)
          done

      - name: Run Cargo Clippy
        run: |
          for dir in $(find crates examples -name "Cargo.toml" -exec dirname {} \;); do
            echo "Running Clippy in $dir"
            (cd "$dir" && cargo clippy -- -D warnings)
          done
